---
title: "RCR & Scholarly Activity In-Person Training"
format: 
  revealjs:
    theme: [default]
    slide-number: true
    preview-links: auto
    logo: images/ORI.png
    footer: Questions? <tkfr222@uky.edu>
    transition: fade
    navigation-mode: vertical
editor: visual
self-contained: false
---

# Introduction

## Why is UK mandating RCR training?

_“As a public institution of higher education, public confidence in the responsible conduct of research (RCR) by faculty, staff and students is critical.  We must promote and maintain a culture that is supported by an infrastructure that educates and assists in the ethical conduct of research.”_

Lisa Cassis PhD, UK Vice President for Research (VPR)

___ 

UK has had research misconduct cases in the past few years due to a failure of some researchers to follow Responsible Conduct of Research.

::: {.r-fit-text}
This effects:

- The reputation of UK and its researchers;
- Researchers/research personnel affiliated with the wrongdoer;
- Personnel managing the process for research misconduct;
- Researchers doing honest work that could have received the research funding used;
- General public if faulty data is used in publications is relied upon by the medical community, product development, etc.
:::

## Areas of RCR Training at UK

- Mentoring
- **Conflict of Interest**
- **Peer Review**
- Research Misconduct
- Data Management
- Reproducibility

## What Will The Rest of the Day Look Like?

- Observe 3 case studies
- Discuss in groups
- Summarize key points

*Must have minimum 1 hour of contact together*

# Case Study One

## Peer Review

A PI is purposely stalling a peer review she has to complete so her colleague can publish ahead of the competitor.  

::: {.r-fit-text}
Through this case, learners will:

- learn about ethical conduct during the peer-review process
- learn how to manage conflicts of interest and bias related to the peer-review process
:::

[Case Study #1](https://rwebmedia.ad.uky.edu/ORI/SecureContent/SecureContent/RCR_Cases/Peer_Review/Case_3/story.html)

## Discussion

::: {.incremental}
1. Sum up the general problem under scrutiny.
2. What aspects of the scenario stood out the most to the group. 
3. Did Lisa act appropriately in telling Bill to publish quickly?
4. Did Lisa act appropriately in delaying the review? In giving a critical and demanding review of the paper?
5. Is there anything Lisa should have done differently when she received the submitted paper?
6. What should Bill have done when given the encouragement to publish?
:::

::: {.notes}
Additional prompts:
- Lisa clearly has a conflict of interest and chooses not to disclose this information. Should Lisa have excused herself from the review?
- Was Lisa acting fairly to the journal she agreed to help?
- Was Lisa acting fairly to the researchers that submitted their work for review?
- Was it ethical to take as long as she did to review the manuscript and then ask for major revisions?
- Did Lisa treat the manuscript as a confidential document? Did she demonstrate a breach in the confidentiality?
- Based on the feedback Lisa gave in the video, can we assume Lisa gave objective and unbiased feedback to the researchers? Do you think Lisa demonstrated any bias while performing her review duties?
- Did Bill act unethically in this scenario?
:::

## Additional Resources

- ORI Peer-review resources: [https://ori.hhs.gov/peer-review-0](https://ori.hhs.gov/peer-review-0)
- ORI Conflict of interest resources: [https://ori.hhs.gov/conflicts-interest-and-commitment](https://ori.hhs.gov/conflicts-interest-and-commitment)
- ORI’s *Introduction to the Responsible Conduct of Research*: [https://ori.hhs.gov/ori-introduction-responsible-conduct-research](https://ori.hhs.gov/ori-introduction-responsible-conduct-research)

# Case Study Two

## Conflict of Interest

An NSF panelist gives a proposal favorable scores even though the proposal was written by her co-PIs. She did not disclose this information to the panel prior to the review.

::: {.r-fit-text}
Through this case, learners will:

- learn about conflicts of interest
- learn the importance of disclosing conflicts of interest
:::

[Case Study #2](https://rwebmedia.ad.uky.edu/ORI/SecureContent/SecureContent/RCR_Cases/Conflict_of_Interest/Case_2/index.html)

## Discussion

::: {.incremental}
1. What are the issues with this scenario?
2. How should the alleged conflict of interest have been handled?
3. Can a reviewer provide both a positive and a negative review?
4. Why would a reviewer fail to disclose a potential conflict of interest?
5. Are there reasons that are excusable?
:::

::: {.notes}
Additional prompts:
- How should you approach a situation in which you have a clear conflict of interest?
- What should you do if you are unsure you have a conflict of interest?
:::

## Additional Resources
::: {.r-fit-text}
- UK ORI’s conflict of interest Q&A webpage: [https://www.research.uky.edu/office-research-integrity/conflict-interest-coi-questionsanswers](https://www.research.uky.edu/office-research-integrity/conflict-interest-coi-questionsanswers)
- UK’s Office of Sponsored Projects COI resources:
  - [https://www.research.uky.edu/office-sponsored-projects-administration/conflict-interest](https://www.research.uky.edu/office-sponsored-projects-administration/conflict-interest)
  - [https://www.research.uky.edu/office-sponsored-projects-administration/training-resources](https://www.research.uky.edu/office-sponsored-projects-administration/training-resources)
- ORI Resources on conflicts of Interest:
  - [https://ori.hhs.gov/conflicts-interest-and-commitment](https://ori.hhs.gov/conflicts-interest-and-commitment)
  - [https://ori.hhs.gov/education/products/ucla/chapter4/default.htm](https://ori.hhs.gov/education/products/ucla/chapter4/default.htm)
  - [https://ori.hhs.gov/brief-overview-conflict-interests](https://ori.hhs.gov/brief-overview-conflict-interests)
  - [https://ori.hhs.gov/education/products/wsu/rcr_training07.html](https://ori.hhs.gov/education/products/wsu/rcr_training07.html)
:::

# Case Study Three

## Research Misconduct

Let's talk plagiarism!

::: {.r-fit-text}
Through this case, learners will:

- learn about ethical issues with regard to plagiarism
- learn about available plagiarism resources 
- consider ethical writing practices
:::

[Case Study #3](https://rwebmedia.ad.uky.edu/ORI/RCR_Cases/I_wrote_it_why_rewrite_it/index.html)

## Discussion
::: {.r-fit-text}
::: {.incremental}
1. Sum up the general problem under scrutiny.
2. What aspects of the scenario stood out the most to the group. 
3. Was the graduate student right to be concerned about this practice?
4. What do you think of the post-doc's explanation for why he used old papers?
5. What might happen if the PI does not change the text before publication.
6. What do you think of GS' decision to not talk to anyone about her concerns?
7. What could happen is she does pursue this line of questioning?
8. What would you do in her place?
:::
:::

::: {.notes}
Additional prompts:
- How would you address suspected plagiarism in your workplace?
- If you suspected someone of engaging in self-plagiarism, would you address the issue the same as you would with plagiarism of someone else’s work? Why or why not?
:::

## Additional Resources

::: {.r-fit-text}
- UK’s Research Misconduct webpage: [https://www.research.uky.edu/research-misconduct](https://www.research.uky.edu/research-misconduct)
- DHHS ORI’s *Introduction to the Responsible Conduct of Research*: [https://ori.hhs.gov/sites/default/files/2018-04/rcrintro.pdf](https://ori.hhs.gov/sites/default/files/2018-04/rcrintro.pdf)
- DHHS ORI’s Avoiding Plagiarism, Self-plagiarism, and Other Questionable Writing Practices: A Guide to Ethical Writing:
- Online plagiarism tools: 
  - Plagiarisma (free online plagiarism checker): [http://plagiarisma.net/](http://plagiarisma.net/)
  - iThenticate (subscription required online plagiarism checker): [https://www.research.uky.edu/research-misconduct/ithenticate-uk](https://www.research.uky.edu/research-misconduct/ithenticate-uk)
  - Plagiarismcheck.org (detects similarities and produces unbiased results; requires a subscription): [https://plagiarismcheck.org/](https://plagiarismcheck.org/)
  - Similarity texter (a text comparison tool): [https://people.f4.htwberlin.de/%7Eweberwu/simtexter/app.html](https://people.f4.htwberlin.de/%7Eweberwu/simtexter/app.html)
- UK ORI's tips to avoid plagiarism video: [https://rwebmedia.ad.uky.edu/ORI/Research_Misconduct/Plagiarism/index.html](https://rwebmedia.ad.uky.edu/ORI/Research_Misconduct/Plagiarism/index.html)
:::

# Feedback

## Reflect

::: {.incremental}
- What were your big takeaways from the training today?
- What lingering questions do you still have regarding the content?
- How might you improve this training speciically for faculty in SIS in the future?
:::

## Case Studies

Post-session RCR Case Study Survey
- [https://uky.az1.qualtrics.com/jfe/form/SV_79CaFBt2jglwtMi](https://uky.az1.qualtrics.com/jfe/form/SV_79CaFBt2jglwtMi)

# Thank you!!
